# Dependencies
markdown:           kramdown 
highlighter:        pygments

# Permalinks
permalink:          pretty

# Setup
title:              Notes
tagline:            'Class notes for Nate Harada'
baseurl:            /

author:
    name:           'Nate Harada'
    url:            http://blog.nateharada.com

paginate:           5

# Custom vars
version:            2.1.0
