# Dependencies
markdown:           kramdown 
highlighter:        pygments

# Permalinks
permalink:          pretty

# Setup
title:              Notes
tagline:            'Class notes for Nate Harada'
baseurl:            /

author:
    name:           'Nate Harada'
    url:            https://blog.nateharada.com

paginate:           5

# Custom vars
version:            2.1.0

# Classes
collections:
    eecs492:
        name:       'Intro to Artifical Intelligence'
        professor:  'Emily Mower Provost'
        semester:   'F2014'
        output:     true
    eecs598:
        name:       'Data Science for Medicine'
        professor:  'Zeeshan Syed'
        semester:   'F2014'
        output:     true
